// voice/src/frontend/angular/components/guide-card.component.ts
import { Component, Input } from "@angular/core";

@Component({
  host: {
    class: "voice-card voice-card-side",
  },
  selector: "article[voiceGuideCard]",
  standalone: true,
  template: `
    <h2>{{ guideTitle }}</h2>
    <ol class="voice-guide-list">
      @for (step of guideSteps; track step) {
        <li>{{ step }}</li>
      }
    </ol>
  `,
})
export class GuideCardComponent {
  @Input({ required: true }) guideSteps!: ReadonlyArray<string>;
  @Input({ required: true }) guideTitle!: string;
}

// voice/src/frontend/svelte/components/GuideCard.svelte
<script lang="ts">
  import {
    VOICE_DEMO_GUIDE_STEPS,
    VOICE_DEMO_GUIDE_TITLE,
  } from "../../../shared/demo";
</script>

<article class="voice-card voice-card-side">
  <h2>{VOICE_DEMO_GUIDE_TITLE}</h2>
  <ol class="voice-guide-list">
    {#each VOICE_DEMO_GUIDE_STEPS as step}
      <li>{step}</li>
    {/each}
  </ol>
</article>
