// voice/src/frontend/angular/components/provider-config-card.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";
import {
  VOICE_MODEL_PROVIDERS,
  VOICE_PROFILES,
  VOICE_ROUTING_MODES,
  VOICE_SPEECH_ENGINES,
  type VoiceModelProvider,
  type VoiceProfileId,
  type VoiceRoutingMode,
  type VoiceSpeechEngine,
} from "../../../shared/demo";

@Component({
  host: {
    class: "voice-card voice-provider-card",
  },
  selector: "article[voiceProviderConfigCard]",
  standalone: true,
  template: `
    <span class="voice-framework-pill">Model Provider</span>
    <h2>Choose the assistant brain</h2>
    <p class="voice-footnote">
      Switch providers before starting the microphone. The voice route receives
      the selected provider on every session.
    </p>
    <label class="voice-provider-select">
      <span>Provider</span>
      <select (change)="modelProviderChange.emit($any($event.target).value)">
        @for (provider of modelProviders; track provider.id) {
          <option
            value="{{ provider.id }}"
            [attr.selected]="provider.id === modelProvider ? '' : null"
          >
            {{ provider.label }}
          </option>
        }
      </select>
    </label>
    <label class="voice-provider-select">
      <span>Voice profile</span>
      <select (change)="profileIdChange.emit($any($event.target).value)">
        @for (profile of voiceProfiles; track profile.id) {
          <option
            value="{{ profile.id }}"
            [attr.selected]="profile.id === profileId ? '' : null"
          >
            {{ profile.label }}
          </option>
        }
      </select>
    </label>
    <label class="voice-provider-select">
      <span>STT routing</span>
      <select (change)="routingModeChange.emit($any($event.target).value)">
        @for (routing of routingModes; track routing.id) {
          <option
            value="{{ routing.id }}"
            [attr.selected]="routing.id === routingMode ? '' : null"
          >
            {{ routing.label }}
          </option>
        }
      </select>
    </label>
    <label class="voice-provider-select">
      <span>Speech engine</span>
      <select (change)="speechEngineChange.emit($any($event.target).value)">
        @for (engine of speechEngines; track engine.id) {
          <option
            value="{{ engine.id }}"
            [attr.selected]="engine.id === speechEngine ? '' : null"
          >
            {{ engine.label }}
          </option>
        }
      </select>
    </label>
    <p class="voice-footnote">
      {{ routingDescription }}
    </p>
  `,
})
export class ProviderConfigCardComponent {
  @Input({ required: true }) modelProvider!: VoiceModelProvider;
  @Input({ required: true }) profileId!: VoiceProfileId;
  @Input({ required: true }) routingDescription!: string;
  @Input({ required: true }) routingMode!: VoiceRoutingMode;
  @Input({ required: true }) speechEngine!: VoiceSpeechEngine;
  @Output() modelProviderChange = new EventEmitter<VoiceModelProvider>();
  @Output() profileIdChange = new EventEmitter<VoiceProfileId>();
  @Output() routingModeChange = new EventEmitter<VoiceRoutingMode>();
  @Output() speechEngineChange = new EventEmitter<VoiceSpeechEngine>();
  modelProviders = VOICE_MODEL_PROVIDERS;
  routingModes = VOICE_ROUTING_MODES;
  speechEngines = VOICE_SPEECH_ENGINES;
  voiceProfiles = VOICE_PROFILES;
}

// voice/src/frontend/svelte/components/ProviderConfigCard.svelte
<script lang="ts">
  import {
    getVoiceProfileLabel,
    VOICE_MODEL_PROVIDERS,
    VOICE_PROFILES,
    VOICE_ROUTING_MODES,
    VOICE_SPEECH_ENGINES,
    type VoiceModelProvider,
    type VoiceProfileId,
    type VoiceRoutingMode,
    type VoiceSpeechEngine,
  } from "../../../shared/demo";

  type ProviderConfigCardProps = {
    modelProvider: VoiceModelProvider;
    onChangeModelProvider: (event: Event) => void;
    onChangeProfileId: (event: Event) => void;
    onChangeRoutingMode: (event: Event) => void;
    onChangeSpeechEngine: (event: Event) => void;
    profileId: VoiceProfileId;
    routingMode: VoiceRoutingMode;
    speechEngine: VoiceSpeechEngine;
  };

  let {
    modelProvider,
    onChangeModelProvider,
    onChangeProfileId,
    onChangeRoutingMode,
    onChangeSpeechEngine,
    profileId,
    routingMode,
    speechEngine,
  }: ProviderConfigCardProps = $props();
</script>

<article class="voice-card voice-provider-card">
  <span class="voice-framework-pill">Model Provider</span>
  <h2>Choose the assistant brain</h2>
  <p class="voice-footnote">
    Switch providers before starting the microphone. The voice route receives
    the selected provider on every session.
  </p>
  <label class="voice-provider-select">
    <span>Provider</span>
    <select value={modelProvider} on:change={onChangeModelProvider}>
      {#each VOICE_MODEL_PROVIDERS as provider}
        <option value={provider.id}>{provider.label}</option>
      {/each}
    </select>
  </label>
  <label class="voice-provider-select">
    <span>Voice profile</span>
    <select value={profileId} on:change={onChangeProfileId}>
      {#each VOICE_PROFILES as profile}
        <option value={profile.id}>{profile.label}</option>
      {/each}
    </select>
  </label>
  <label class="voice-provider-select">
    <span>STT routing</span>
    <select value={routingMode} on:change={onChangeRoutingMode}>
      {#each VOICE_ROUTING_MODES as routing}
        <option value={routing.id}>{routing.label}</option>
      {/each}
    </select>
  </label>
  <label class="voice-provider-select">
    <span>Speech engine</span>
    <select value={speechEngine} on:change={onChangeSpeechEngine}>
      {#each VOICE_SPEECH_ENGINES as engine}
        <option value={engine.id}>{engine.label}</option>
      {/each}
    </select>
  </label>
  <p class="voice-footnote">
    {getVoiceProfileLabel(profileId)} uses {VOICE_PROFILES.find(
      (item) => item.id === profileId,
    )?.description ?? "the selected real-call defaults."}
  </p>
</article>
