// auth/src/frontend/vue/components/Home.vue
<script setup lang="ts">
import { RouterLink } from "vue-router";
import { useAuth } from "../composables/useAuth";
import ProviderLogin from "./ProviderLogin.vue";

const { user } = useAuth();
</script>

<template>
  <section class="auth-content">
    <h1 class="page-heading">Absolute Auth — Vue</h1>
    <template v-if="user">
      <p class="muted">You are signed in as {{ user.email ?? user.sub }}.</p>
      <RouterLink class="btn btn--primary" to="/vue/protected">
        View the protected page
      </RouterLink>
    </template>
    <template v-else>
      <p class="muted">
        Sign in or sign up with any OAuth2 provider to test the flow.
      </p>
      <div class="card login-card text-left">
        <ProviderLogin action="login" />
      </div>
    </template>
  </section>
</template>

// auth/src/frontend/react/components/Home.tsx
import { Link } from "react-router";
import type { AuthUser } from "../../shared/types";
import { ProviderLogin } from "./ProviderLogin";

export const Home = ({ user }: { user: AuthUser | null }) => (
  <section className="auth-content">
    <h1 className="page-heading">Absolute Auth — React</h1>
    {user ? (
      <>
        <p className="muted">You are signed in as {user.email ?? user.sub}.</p>
        <Link className="btn btn--primary" to="/react/protected">
          View the protected page
        </Link>
      </>
    ) : (
      <>
        <p className="muted">
          Sign in or sign up with any OAuth2 provider to test the flow.
        </p>
        <div className="card login-card text-left">
          <ProviderLogin action="login" />
        </div>
      </>
    )}
  </section>
);
