// auth/src/frontend/svelte/components/Navbar.svelte
<script lang="ts">
  import Link from "@absolutejs/absolute/svelte/router/Link.svelte";
  import { goto } from "@absolutejs/absolute/svelte/router";
  import { NAV_ITEMS } from "../../shared/navData";
  import { authState, signOutUser } from "../stores/auth.svelte";

  let menuOpen = $state(false);
  const base = "/svelte";
  const linkTo = (path: string) => (path === "" ? base : `${base}/${path}`);

  const onSignOut = async () => {
    await signOutUser();
    menuOpen = false;
    goto(base);
  };
</script>

<header class="navbar">
  <Link to={base} class="navbar__brand">
    <img alt="" src="/assets/png/absolutejs-temp.png" />
    Absolute Auth
  </Link>

  <nav class="navbar__links">
    {#each NAV_ITEMS as item (item.path)}
      <Link to={linkTo(item.path)} class="navbar__link">{item.label}</Link>
    {/each}
  </nav>

  <div class="navbar__user">
    {#if authState.user}
      <span class="muted">
        {authState.user.email ?? authState.user.first_name ?? "Account"}
      </span>
      <button class="btn btn--ghost btn--sm" type="button" onclick={onSignOut}>
        Sign out
      </button>
    {:else}
      <Link to={base} class="btn btn--primary btn--sm">Sign in</Link>
    {/if}
    <button
      class="hamburger"
      type="button"
      aria-label="Toggle menu"
      onclick={() => (menuOpen = !menuOpen)}
    >
      <span class="hamburger__bar"></span>
      <span class="hamburger__bar"></span>
      <span class="hamburger__bar"></span>
    </button>
  </div>

  <div class={menuOpen ? "hamburger-menu is-open" : "hamburger-menu"}>
    <div class="hamburger-menu__header">
      <strong>Menu</strong>
      <button
        class="btn btn--ghost btn--sm"
        type="button"
        onclick={() => (menuOpen = false)}
      >
        Close
      </button>
    </div>
    {#each NAV_ITEMS as item (item.path)}
      <Link to={linkTo(item.path)} class="navbar__link">{item.label}</Link>
    {/each}
    {#if authState.user}
      <button class="btn btn--ghost" type="button" onclick={onSignOut}>
        Sign out
      </button>
    {/if}
  </div>
</header>

// auth/src/frontend/react/components/Navbar.tsx
import { useState } from "react";
import { Link, useLocation } from "react-router";
import { NAV_ITEMS } from "../../shared/navData";
import type { AuthUser } from "../../shared/types";

type NavbarProps = {
  basePath: string;
  onSignOut: () => void;
  user: AuthUser | null;
};

export const Navbar = ({ basePath, onSignOut, user }: NavbarProps) => {
  const [menuOpen, setMenuOpen] = useState(false);
  const { pathname } = useLocation();

  const linkTo = (path: string) =>
    path === "" ? basePath : `${basePath}/${path}`;

  const renderLinks = (onNavigate?: () => void) =>
    NAV_ITEMS.map((item) => {
      const target = linkTo(item.path);

      return (
        <Link
          aria-current={pathname === target ? "page" : undefined} className="navbar__link" key={item.path} onClick={onNavigate} to={target}
        >
          {item.label}
        </Link>
      );
    });

  const greeting = user?.email ?? user?.first_name ?? "Account";

  return (
    <header className="navbar">
      <Link className="navbar__brand" to={basePath}>
        <img alt="" src="/assets/png/absolutejs-temp.png" />
        Absolute Auth
      </Link>

      <nav className="navbar__links">{renderLinks()}</nav>

      <div className="navbar__user">
        {user ? (
          <>
            <span className="muted">{greeting}</span>
            <button
              className="btn btn--ghost btn--sm"
              onClick={onSignOut}
              type="button"
            >
              Sign out
            </button>
          </>
        ) : (
          <Link className="btn btn--primary btn--sm" to={basePath}>
            Sign in
          </Link>
        )}
        <button
          aria-label="Toggle menu"
          className="hamburger"
          onClick={() => setMenuOpen((open) => !open)}
          type="button"
        >
          <span className="hamburger__bar" />
          <span className="hamburger__bar" />
          <span className="hamburger__bar" />
        </button>
      </div>

      <div className={menuOpen ? "hamburger-menu is-open" : "hamburger-menu"}>
        <div className="hamburger-menu__header">
          <strong>Menu</strong>
          <button
            className="btn btn--ghost btn--sm"
            onClick={() => setMenuOpen(false)}
            type="button"
          >
            Close
          </button>
        </div>
        {renderLinks(() => setMenuOpen(false))}
        {user ? (
          <button
            className="btn btn--ghost"
            onClick={() => {
              setMenuOpen(false);
              onSignOut();
            }}
            type="button"
          >
            Sign out
          </button>
        ) : null}
      </div>
    </header>
  );
};
