// auth/src/frontend/vue/components/NotAuthorized.vue
<script setup lang="ts">
import { RouterLink } from "vue-router";
</script>

<template>
  <section class="auth-content">
    <h1 class="page-heading">Not authorized</h1>
    <p class="muted">You need to sign in to view this page.</p>
    <RouterLink class="btn btn--primary" to="/vue">Go to sign in</RouterLink>
  </section>
</template>

// auth/src/frontend/react/components/NotAuthorized.tsx
import { Link } from "react-router";

export const NotAuthorized = () => (
  <section className="auth-content">
    <h1 className="page-heading">Not authorized</h1>
    <p className="muted">You need to sign in to view this page.</p>
    <Link className="btn btn--primary" to="/react">
      Go to sign in
    </Link>
  </section>
);
