// auth/src/frontend/svelte/components/Protected.svelte
<script lang="ts">
  import { authState } from "../stores/auth.svelte";
  import HighlightedJson from "./HighlightedJson.svelte";
  import NotAuthorized from "./NotAuthorized.svelte";
</script>

{#if authState.loading}
  <section class="auth-content">
    <p class="muted">Checking your session…</p>
  </section>
{:else if !authState.user}
  <NotAuthorized />
{:else}
  <section class="auth-section stack">
    <div>
      <h1 class="page-heading">Protected page</h1>
      <p class="muted">
        Your authenticated session resolves to this user record.
      </p>
    </div>
    <HighlightedJson data={authState.user} />
  </section>
{/if}

// auth/src/frontend/react/components/Protected.tsx
import type { AuthUser } from "../../shared/types";
import { HighlightedJson } from "./HighlightedJson";
import { NotAuthorized } from "./NotAuthorized";

type ProtectedProps = {
  loading: boolean;
  user: AuthUser | null;
};

export const Protected = ({ loading, user }: ProtectedProps) => {
  if (loading) {
    return (
      <section className="auth-content">
        <p className="muted">Checking your session…</p>
      </section>
    );
  }

  if (!user) {
    return <NotAuthorized />;
  }

  return (
    <section className="auth-section stack">
      <div>
        <h1 className="page-heading">Protected page</h1>
        <p className="muted">
          Your authenticated session resolves to this user record.
        </p>
      </div>
      <HighlightedJson data={user} />
    </section>
  );
};
