// auth/src/frontend/react/components/Home.tsx
import { Link } from "react-router";
import type { AuthUser } from "../../shared/types";
import { ProviderLogin } from "./ProviderLogin";

export const Home = ({ user }: { user: AuthUser | null }) => (
  <section className="auth-content">
    <h1 className="page-heading">Absolute Auth — React</h1>
    {user ? (
      <>
        <p className="muted">You are signed in as {user.email ?? user.sub}.</p>
        <Link className="btn btn--primary" to="/react/protected">
          View the protected page
        </Link>
      </>
    ) : (
      <>
        <p className="muted">
          Sign in or sign up with any OAuth2 provider to test the flow.
        </p>
        <div className="card login-card text-left">
          <ProviderLogin action="login" />
        </div>
      </>
    )}
  </section>
);

// auth/src/frontend/svelte/components/Home.svelte
<script lang="ts">
  import Link from "@absolutejs/absolute/svelte/router/Link.svelte";
  import { authState } from "../stores/auth.svelte";
  import ProviderLogin from "./ProviderLogin.svelte";
</script>

<section class="auth-content">
  <h1 class="page-heading">Absolute Auth — Svelte</h1>
  {#if authState.user}
    <p class="muted">
      You are signed in as {authState.user.email ?? authState.user.sub}.
    </p>
    <Link to="/svelte/protected" class="btn btn--primary">
      View the protected page
    </Link>
  {:else}
    <p class="muted">
      Sign in or sign up with any OAuth2 provider to test the flow.
    </p>
    <div class="card login-card text-left">
      <ProviderLogin action="login" />
    </div>
  {/if}
</section>
