// auth/src/frontend/react/components/NotAuthorized.tsx
import { Link } from "react-router";

export const NotAuthorized = () => (
  <section className="auth-content">
    <h1 className="page-heading">Not authorized</h1>
    <p className="muted">You need to sign in to view this page.</p>
    <Link className="btn btn--primary" to="/react">
      Go to sign in
    </Link>
  </section>
);

// auth/src/frontend/svelte/components/NotAuthorized.svelte
<script lang="ts">
  import Link from "@absolutejs/absolute/svelte/router/Link.svelte";
</script>

<section class="auth-content">
  <h1 class="page-heading">Not authorized</h1>
  <p class="muted">You need to sign in to view this page.</p>
  <Link to="/svelte" class="btn btn--primary">Go to sign in</Link>
</section>
