// auth/src/frontend/react/components/LinkedProvidersPanel.tsx
import { useState } from "react";
import { removeBinding, removeGrant } from "../../shared/authClient";
import type { LinkedProviderPayload } from "../../shared/types";
import { useLinkedProviders } from "../hooks/useLinkedProviders";
import { BindingRow } from "./BindingRow";
import { GrantRow } from "./GrantRow";
import { useToast } from "./toast/ToastProvider";

export const LinkedProvidersPanel = () => {
  const { error, loading, payload, refresh, setPayload } =
    useLinkedProviders(true);
  const { addToast } = useToast();
  const [busyId, setBusyId] = useState<string | null>(null);

  const run = async (
    id: string,
    action: () => Promise<LinkedProviderPayload>,
    success: string,
  ) => {
    setBusyId(id);
    try {
      setPayload(await action());
      addToast(success, "success");
    } catch (caught) {
      addToast(
        caught instanceof Error ? caught.message : "Action failed",
        "error",
      );
    } finally {
      setBusyId(null);
    }
  };

  return (
    <div className="panel">
      <div className="panel__header">
        <div>
          <h2 className="panel__title">Linked connectors</h2>
          <p className="muted">
            OAuth grants and the external accounts discovered for them.
          </p>
        </div>
        <button
          className="btn btn--ghost btn--sm"
          onClick={() => void refresh()}
          type="button"
        >
          Refresh
        </button>
      </div>

      {error && <div className="error-banner">{error}</div>}
      {loading && !payload && <p className="muted">Loading connectors…</p>}

      <h3 className="provider-heading">External accounts</h3>
      {payload && payload.bindings.length === 0 && (
        <div className="empty-state">No external accounts linked.</div>
      )}
      <div className="entity-list">
        {payload?.bindings.map((binding) => (
          <BindingRow
            binding={binding}
            busy={busyId === binding.id}
            key={binding.id}
            onRemove={() =>
              run(
                binding.id,
                () => removeBinding(binding.id),
                "Binding removed",
              )
            }
          />
        ))}
      </div>

      <h3 className="provider-heading">Grants</h3>
      {payload && payload.grants.length === 0 && (
        <div className="empty-state">No connector grants yet.</div>
      )}
      <div className="entity-list">
        {payload?.grants.map((grant) => (
          <GrantRow
            busy={busyId === grant.id}
            grant={grant}
            key={grant.id}
            onRemove={() =>
              run(grant.id, () => removeGrant(grant.id), "Grant removed")
            }
          />
        ))}
      </div>
    </div>
  );
};

// auth/src/frontend/angular/components/linked-providers-panel/linked-providers-panel.ts
import { CommonModule } from "@angular/common";
import { Component, inject, signal } from "@angular/core";
import {
  fetchLinkedProviders,
  removeBinding,
  removeGrant,
} from "../../../shared/authClient";
import type { LinkedProviderPayload } from "../../../shared/types";
import { ToastService } from "../../services/toast.service";

@Component({
  imports: [CommonModule],
  selector: "auth-linked-providers-panel",
  standalone: true,
  templateUrl: "./linked-providers-panel.html",
})
export class LinkedProvidersPanelComponent {
  private readonly toast = inject(ToastService);

  readonly payload = signal<LinkedProviderPayload | null>(null);
  readonly error = signal<string | null>(null);
  readonly busyId = signal<string | null>(null);

  readonly removeBinding = removeBinding;
  readonly removeGrant = removeGrant;

  constructor() {
    void this.refresh();
  }

  formatTime(value: number | undefined) {
    return value === undefined ? "—" : new Date(value).toLocaleString();
  }

  async refresh() {
    this.error.set(null);
    try {
      this.payload.set(await fetchLinkedProviders());
    } catch (caught) {
      this.error.set(
        caught instanceof Error ? caught.message : "Failed to load connectors",
      );
    }
  }

  async run(
    id: string,
    action: Promise<LinkedProviderPayload>,
    success: string,
  ) {
    this.busyId.set(id);
    try {
      this.payload.set(await action);
      this.toast.add(success, "success");
    } catch (caught) {
      this.toast.add(
        caught instanceof Error ? caught.message : "Action failed",
        "error",
      );
    } finally {
      this.busyId.set(null);
    }
  }
}
