// auth/src/frontend/svelte/components/Protected.svelte
<script lang="ts">
  import { authState } from "../stores/auth.svelte";
  import HighlightedJson from "./HighlightedJson.svelte";
  import NotAuthorized from "./NotAuthorized.svelte";
</script>

{#if authState.loading}
  <section class="auth-content">
    <p class="muted">Checking your session…</p>
  </section>
{:else if !authState.user}
  <NotAuthorized />
{:else}
  <section class="auth-section stack">
    <div>
      <h1 class="page-heading">Protected page</h1>
      <p class="muted">
        Your authenticated session resolves to this user record.
      </p>
    </div>
    <HighlightedJson data={authState.user} />
  </section>
{/if}

// auth/src/frontend/vue/components/Protected.vue
<script setup lang="ts">
import { useAuth } from "../composables/useAuth";
import HighlightedJson from "./HighlightedJson.vue";
import NotAuthorized from "./NotAuthorized.vue";

const { loading, user } = useAuth();
</script>

<template>
  <section v-if="loading" class="auth-content">
    <p class="muted">Checking your session…</p>
  </section>
  <NotAuthorized v-else-if="!user" />
  <section v-else class="auth-section stack">
    <div>
      <h1 class="page-heading">Protected page</h1>
      <p class="muted">
        Your authenticated session resolves to this user record.
      </p>
    </div>
    <HighlightedJson :data="user" />
  </section>
</template>
