// voice/src/frontend/angular/components/demo-chrome.component.ts
import { Component } from "@angular/core";

@Component({
  host: {
    class: "voice-demo-page",
  },
  selector: "div[voiceDemoChrome]",
  standalone: true,
  template: `
    <header>
      <a class="logo" href="/">
        <img
          alt="AbsoluteJS"
          height="24"
          src="/assets/png/absolutejs-temp.png"
        />
        AbsoluteJS
      </a>
      <nav>
        <a href="/">React</a>
        <a href="/svelte">Svelte</a>
        <a href="/vue">Vue</a>
        <a href="/angular" class="active">Angular</a>
        <a href="/html">HTML</a>
        <a href="/htmx">HTMX</a>
        <a href="/reviews">Reviews</a>
        <a href="/traces">Traces</a>
        <a href="/carriers">Carriers</a>
        <a href="/phone-agent">Phone Agent</a>
      </nav>
    </header>
    <main class="voice-shell">
      <section class="voice-grid">
        <ng-content></ng-content>
      </section>
      <p class="footer">
        <img src="/assets/png/absolutejs-temp.png" alt="" />
        Powered by
        <a
          href="https://absolutejs.com"
          target="_blank"
          rel="noopener noreferrer"
          >AbsoluteJS</a
        >
      </p>
    </main>
  `,
})
export class DemoChromeComponent {}

// voice/src/frontend/vue/components/DemoChrome.vue
<script setup lang="ts">
import { FRAMEWORKS } from "../../../shared/demo";
</script>

<template>
  <div class="voice-demo-page">
    <header>
      <a class="logo" href="/">
        <img
          alt="AbsoluteJS"
          height="24"
          src="/assets/png/absolutejs-temp.png"
        />
        AbsoluteJS
      </a>
      <nav>
        <a
          v-for="framework in FRAMEWORKS"
          :key="framework.id"
          :class="{ active: framework.id === 'vue' }"
          :href="framework.href"
        >
          {{ framework.label }}
        </a>
        <a href="/reviews">Reviews</a>
        <a href="/traces">Traces</a>
        <a href="/carriers">Carriers</a>
        <a href="/phone-agent">Phone Agent</a>
      </nav>
    </header>
    <main class="voice-shell">
      <section class="voice-grid">
        <slot></slot>
      </section>
      <p class="footer">
        <img src="/assets/png/absolutejs-temp.png" alt="" />
        Powered by
        <a
          href="https://absolutejs.com"
          target="_blank"
          rel="noopener noreferrer"
          >AbsoluteJS</a
        >
      </p>
    </main>
  </div>
</template>
