// voice/src/frontend/svelte/components/GuideCard.svelte
<script lang="ts">
  import {
    VOICE_DEMO_GUIDE_STEPS,
    VOICE_DEMO_GUIDE_TITLE,
  } from "../../../shared/demo";
</script>

<article class="voice-card voice-card-side">
  <h2>{VOICE_DEMO_GUIDE_TITLE}</h2>
  <ol class="voice-guide-list">
    {#each VOICE_DEMO_GUIDE_STEPS as step}
      <li>{step}</li>
    {/each}
  </ol>
</article>

// voice/src/frontend/vue/components/GuideCard.vue
<script setup lang="ts">
import {
  VOICE_DEMO_GUIDE_STEPS,
  VOICE_DEMO_GUIDE_TITLE,
} from "../../../shared/demo";
</script>

<template>
  <article class="voice-card voice-card-side">
    <h2>{{ VOICE_DEMO_GUIDE_TITLE }}</h2>
    <ol class="voice-guide-list">
      <li v-for="step in VOICE_DEMO_GUIDE_STEPS" :key="step">
        {{ step }}
      </li>
    </ol>
  </article>
</template>
