// spa/src/frontend/vue/components/Profile.vue
<template>
  <div>
    <h2>Profile</h2>
    <p>
      Notice the sidebar didn't reload, the click counter above is intact,
      and the URL bar shows <code>/vue/profile</code>. That's
      intra-framework SPA — the framework's own router doing what it
      already does best, with zero wiring code in your page.
    </p>
  </div>
</template>

// spa/src/frontend/react/components/Profile.tsx
export const Profile = () => (
  <div>
    <h2>Profile</h2>
    <p>
      Notice the sidebar didn&apos;t reload, the click counter above is intact,
      and the URL bar shows <code>/react/profile</code>. That&apos;s
      intra-framework SPA — the framework&apos;s own router doing what it
      already does best.
    </p>
  </div>
);
