// voice/src/frontend/svelte/components/DemoChrome.svelte
<script lang="ts">
  import Head from "@absolutejs/absolute/svelte/components/Head.js";
  import { FRAMEWORKS } from "../../../shared/demo";

  type DemoChromeProps = {
    children: import("svelte").Snippet;
    cssPath?: string;
  };

  let { children, cssPath }: DemoChromeProps = $props();
</script>

<Head
  title="AbsoluteJS Voice Test - Svelte"
  description="AbsoluteJS chat-style voice demo with guided and general modes in Svelte."
  {cssPath}
/>

<div class="voice-demo-page">
  <header>
    <a class="logo" href="/">
      <img src="/assets/png/absolutejs-temp.png" height="24" alt="AbsoluteJS" />
      AbsoluteJS
    </a>
    <nav>
      {#each FRAMEWORKS as framework}
        <a class:active={framework.id === "svelte"} href={framework.href}>
          {framework.label}
        </a>
      {/each}
      <a href="/reviews">Reviews</a>
      <a href="/traces">Traces</a>
      <a href="/carriers">Carriers</a>
      <a href="/phone-agent">Phone Agent</a>
    </nav>
  </header>
  <main class="voice-shell">
    <section class="voice-grid">
      {@render children()}
    </section>
    <p class="footer">
      <img src="/assets/png/absolutejs-temp.png" alt="" />
      Powered by
      <a href="https://absolutejs.com" target="_blank" rel="noopener noreferrer"
        >AbsoluteJS</a
      >
    </p>
  </main>
</div>

// voice/src/frontend/react/components/DemoChrome.tsx
import { Head } from "@absolutejs/absolute/react/components";
import type { ReactNode } from "react";
import { FRAMEWORKS } from "../../../shared/demo";

type DemoChromeProps = {
  children: ReactNode;
  cssPath?: string;
};

export const DemoChrome = (props: DemoChromeProps) => (
  <html lang="en">
    <Head
      cssPath={props.cssPath}
      description="AbsoluteJS chat-style voice demo with guided and general modes in React."
      title="AbsoluteJS Voice Test - React"
    />
    <body className="voice-demo-page">
      <header>
        <a className="logo" href="/">
          <img
            alt="AbsoluteJS"
            height={24}
            src="/assets/png/absolutejs-temp.png"
          />
          AbsoluteJS
        </a>
        <nav>
          {FRAMEWORKS.map((framework) => (
            <a
              key={framework.id}
              className={framework.id === "react" ? "active" : undefined}
              href={framework.href}
            >
              {framework.label}
            </a>
          ))}
          <a href="/reviews">Reviews</a>
          <a href="/traces">Traces</a>
          <a href="/carriers">Carriers</a>
          <a href="/phone-agent">Phone Agent</a>
        </nav>
      </header>
      <main className="voice-shell">
        <section className="voice-grid">{props.children}</section>
        <p className="footer">
          <img alt="" src="/assets/png/absolutejs-temp.png" />
          Powered by{" "}
          <a
            href="https://absolutejs.com"
            rel="noopener noreferrer"
            target="_blank"
          >
            AbsoluteJS
          </a>
        </p>
      </main>
    </body>
  </html>
);
