// voice/src/frontend/vue/components/GuideCard.vue
<script setup lang="ts">
import {
  VOICE_DEMO_GUIDE_STEPS,
  VOICE_DEMO_GUIDE_TITLE,
} from "../../../shared/demo";
</script>

<template>
  <article class="voice-card voice-card-side">
    <h2>{{ VOICE_DEMO_GUIDE_TITLE }}</h2>
    <ol class="voice-guide-list">
      <li v-for="step in VOICE_DEMO_GUIDE_STEPS" :key="step">
        {{ step }}
      </li>
    </ol>
  </article>
</template>

// voice/src/frontend/react/components/GuideCard.tsx
import {
  VOICE_DEMO_GUIDE_STEPS,
  VOICE_DEMO_GUIDE_TITLE,
} from "../../../shared/demo";

export const GuideCard = () => (
  <article className="voice-card voice-card-side">
    <h2>{VOICE_DEMO_GUIDE_TITLE}</h2>
    <ol className="voice-guide-list">
      {VOICE_DEMO_GUIDE_STEPS.map((step) => (
        <li key={step}>{step}</li>
      ))}
    </ol>
  </article>
);
