// voice/src/frontend/vue/components/ProviderConfigCard.vue
<script setup lang="ts">
import {
  getVoiceProfileLabel,
  VOICE_MODEL_PROVIDERS,
  VOICE_PROFILES,
  VOICE_ROUTING_MODES,
  VOICE_SPEECH_ENGINES,
  type VoiceModelProvider,
  type VoiceProfileId,
  type VoiceRoutingMode,
  type VoiceSpeechEngine,
} from "../../../shared/demo";

type ProviderConfigCardProps = {
  modelProvider: VoiceModelProvider;
  onChangeModelProvider: (event: Event) => void;
  onChangeProfileId: (event: Event) => void;
  onChangeRoutingMode: (event: Event) => void;
  onChangeSpeechEngine: (event: Event) => void;
  profileId: VoiceProfileId;
  routingMode: VoiceRoutingMode;
  speechEngine: VoiceSpeechEngine;
};

defineProps<ProviderConfigCardProps>();
</script>

<template>
  <article class="voice-card voice-provider-card">
    <span class="voice-framework-pill">Model Provider</span>
    <h2>Choose the assistant brain</h2>
    <p class="voice-footnote">
      Switch providers before starting the microphone. The voice route receives
      the selected provider on every session.
    </p>
    <label class="voice-provider-select">
      <span>Provider</span>
      <select :value="modelProvider" @change="onChangeModelProvider">
        <option
          v-for="provider in VOICE_MODEL_PROVIDERS"
          :key="provider.id"
          :value="provider.id"
        >
          {{ provider.label }}
        </option>
      </select>
    </label>
    <label class="voice-provider-select">
      <span>Voice profile</span>
      <select :value="profileId" @change="onChangeProfileId">
        <option
          v-for="profile in VOICE_PROFILES"
          :key="profile.id"
          :value="profile.id"
        >
          {{ profile.label }}
        </option>
      </select>
    </label>
    <label class="voice-provider-select">
      <span>STT routing</span>
      <select :value="routingMode" @change="onChangeRoutingMode">
        <option
          v-for="routing in VOICE_ROUTING_MODES"
          :key="routing.id"
          :value="routing.id"
        >
          {{ routing.label }}
        </option>
      </select>
    </label>
    <label class="voice-provider-select">
      <span>Speech engine</span>
      <select :value="speechEngine" @change="onChangeSpeechEngine">
        <option
          v-for="engine in VOICE_SPEECH_ENGINES"
          :key="engine.id"
          :value="engine.id"
        >
          {{ engine.label }}
        </option>
      </select>
    </label>
    <p class="voice-footnote">
      {{
        getVoiceProfileLabel(profileId) +
        " uses " +
        (VOICE_PROFILES.find((item) => item.id === profileId)?.description ??
          "the selected real-call defaults.")
      }}
    </p>
  </article>
</template>

// voice/src/frontend/react/components/ProviderConfigCard.tsx
import {
  getVoiceProfileLabel,
  VOICE_MODEL_PROVIDERS,
  VOICE_PROFILES,
  VOICE_ROUTING_MODES,
  VOICE_SPEECH_ENGINES,
  type VoiceModelProvider,
  type VoiceProfileId,
  type VoiceRoutingMode,
  type VoiceSpeechEngine,
} from "../../../shared/demo";

type ProviderConfigCardProps = {
  changeModelProvider: (provider: VoiceModelProvider) => void;
  changeProfileId: (nextProfileId: VoiceProfileId) => void;
  changeRoutingMode: (routing: VoiceRoutingMode) => void;
  changeSpeechEngine: (engine: VoiceSpeechEngine) => void;
  modelProvider: VoiceModelProvider;
  profileId: VoiceProfileId;
  routingMode: VoiceRoutingMode;
  speechEngine: VoiceSpeechEngine;
};

export const ProviderConfigCard = (props: ProviderConfigCardProps) => (
  <article className="voice-card voice-provider-card">
    <span className="voice-framework-pill">Model Provider</span>
    <h2>Choose the assistant brain</h2>
    <p className="voice-footnote">
      Switch providers before starting the microphone. The voice route receives
      the selected provider on every session.
    </p>
    <label className="voice-provider-select">
      <span>Provider</span>
      <select
        value={props.modelProvider}
        onChange={(event) =>
          props.changeModelProvider(
            event.currentTarget.value as VoiceModelProvider,
          )
        }
      >
        {VOICE_MODEL_PROVIDERS.map((provider) => (
          <option key={provider.id} value={provider.id}>
            {provider.label}
          </option>
        ))}
      </select>
    </label>
    <label className="voice-provider-select">
      <span>Voice profile</span>
      <select
        value={props.profileId}
        onChange={(event) =>
          props.changeProfileId(event.currentTarget.value as VoiceProfileId)
        }
      >
        {VOICE_PROFILES.map((profile) => (
          <option key={profile.id} value={profile.id}>
            {profile.label}
          </option>
        ))}
      </select>
    </label>
    <label className="voice-provider-select">
      <span>STT routing</span>
      <select
        value={props.routingMode}
        onChange={(event) =>
          props.changeRoutingMode(event.currentTarget.value as VoiceRoutingMode)
        }
      >
        {VOICE_ROUTING_MODES.map((routing) => (
          <option key={routing.id} value={routing.id}>
            {routing.label}
          </option>
        ))}
      </select>
    </label>
    <label className="voice-provider-select">
      <span>Speech engine</span>
      <select
        value={props.speechEngine}
        onChange={(event) =>
          props.changeSpeechEngine(
            event.currentTarget.value as VoiceSpeechEngine,
          )
        }
      >
        {VOICE_SPEECH_ENGINES.map((engine) => (
          <option key={engine.id} value={engine.id}>
            {engine.label}
          </option>
        ))}
      </select>
    </label>
    <p className="voice-footnote">
      {getVoiceProfileLabel(props.profileId)} uses{" "}
      {VOICE_PROFILES.find((item) => item.id === props.profileId)
        ?.description ?? "the selected real-call defaults."}
    </p>
  </article>
);
