// service-worker/src/frontend/vue/components/Nav.vue
<script setup lang="ts">
defineOptions({ name: "Nav" });
</script>

<template>
  <header>
    <a href="/vue" class="logo">
      <img src="/assets/png/absolutejs-temp.png" height="24" alt="AbsoluteJS" />
      AbsoluteJS
    </a>
    <nav>
      <a href="/">React</a>
      <a href="/svelte">Svelte</a>
      <a href="/vue" class="active">Vue</a>
      <a href="/angular">Angular</a>
      <a href="/html">HTML</a>
    </nav>
  </header>
</template>

// sync/src/frontend/react/components/Nav.tsx
type NavProps = {
  active?: string;
};

export const Nav = ({ active }: NavProps) => (
  <header>
    <a className="logo" href="/">
      <img alt="AbsoluteJS" height={24} src="/assets/png/absolutejs-temp.png" />
      AbsoluteJS
    </a>
    <nav>
      <a className={active === "/" ? "active" : ""} href="/">
        React
      </a>
      <a className={active === "/svelte" ? "active" : ""} href="/svelte">
        Svelte
      </a>
      <a className={active === "/vue" ? "active" : ""} href="/vue">
        Vue
      </a>
      <a className={active === "/angular" ? "active" : ""} href="/angular">
        Angular
      </a>
      <a className={active === "/html" ? "active" : ""} href="/html">
        HTML
      </a>
      <a className={active === "/htmx" ? "active" : ""} href="/htmx">
        HTMX
      </a>
    </nav>
  </header>
);
