// service-worker/src/frontend/react/components/PingCard.tsx
import { useCallback, useState } from "react";
import { PING_COUNT } from "../../constants";

type PingResult = { index: number; latency: number };

const MAX_PING_MS = 50;
const PING_DELAY_MS = 200;
const PERCENT = 100;

export const PingCard = ({ swReady }: { swReady: boolean }) => {
  const [pinging, setPinging] = useState(false);
  const [results, setResults] = useState<PingResult[]>([]);

  const runPing = useCallback(() => {
    const serviceWorker = navigator.serviceWorker?.controller;
    if (!serviceWorker) return;
    setPinging(true);
    setResults([]);
    let count = 0;

    const sendPing = () => {
      const start = performance.now();
      const handler = (event: MessageEvent) => {
        if (event.data.type !== "pong") return;

        const latency = Math.round(performance.now() - start);
        count++;
        setResults((prev) => [...prev, { index: count, latency }]);
        navigator.serviceWorker.removeEventListener("message", handler);
        if (count >= PING_COUNT) {
          setPinging(false);

          return;
        }
        setTimeout(sendPing, PING_DELAY_MS);
      };
      navigator.serviceWorker.addEventListener("message", handler);
      serviceWorker.postMessage({ type: "ping" });
    };

    sendPing();
  }, []);

  const avgLatency =
    results.length > 0
      ? Math.round(
          results.reduce((sum, result) => sum + result.latency, 0) /
            results.length,
        )
      : null;

  return (
    <div className="sw-card">
      <div className="card-title">Message Channel</div>
      <p className="card-desc">
        Ping the service worker and measure round-trip latency.
      </p>
      <button
        className={pinging ? "loading" : ""}
        disabled={!swReady || pinging}
        onClick={runPing}
      >
        {pinging
          ? `Pinging (${results.length}/${PING_COUNT})`
          : `Send ${PING_COUNT} Pings`}
      </button>
      {results.length > 0 && (
        <div className="ping-results">
          {results.map((result) => (
            <div className="ping-row" key={result.index}>
              <div className="ping-bar-track">
                <div
                  className="ping-bar-fill"
                  style={{
                    width: `${Math.min((result.latency / MAX_PING_MS) * PERCENT, PERCENT)}%`,
                  }}
                />
              </div>
              <span className="ping-label">{result.latency}ms</span>
            </div>
          ))}
        </div>
      )}
      <div className="sw-result">
        <div className="result-row">
          <span>Avg Latency</span>
          <span>{avgLatency !== null ? `${avgLatency}ms` : "\u2014"}</span>
        </div>
        <div className="result-row">
          <span>Pings</span>
          <span>
            {results.length} / {PING_COUNT}
          </span>
        </div>
      </div>
    </div>
  );
};

// service-worker/src/frontend/vue/components/PingCard.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import { PING_COUNT } from "../../constants";

defineProps<{ swReady: boolean }>();

type PingResult = { index: number; latency: number };
const MAX_PING_MS = 50;

const pinging = ref(false);
const results = ref<PingResult[]>([]);

const avgLatency = computed(() =>
  results.value.length > 0
    ? Math.round(
        results.value.reduce((s, r) => s + r.latency, 0) / results.value.length,
      )
    : null,
);

function runPing() {
  const sw = navigator.serviceWorker?.controller;
  if (!sw) return;
  pinging.value = true;
  results.value = [];
  let count = 0;

  const sendPing = () => {
    const start = performance.now();
    const handler = (event: MessageEvent) => {
      if (event.data.type === "pong") {
        const latency = Math.round(performance.now() - start);
        count++;
        results.value = [...results.value, { index: count, latency }];
        navigator.serviceWorker.removeEventListener("message", handler);
        if (count < PING_COUNT) {
          setTimeout(sendPing, 200);
        } else {
          pinging.value = false;
        }
      }
    };
    navigator.serviceWorker.addEventListener("message", handler);
    sw.postMessage({ type: "ping" });
  };

  sendPing();
}
</script>

<template>
  <div class="sw-card">
    <div class="card-title">Message Channel</div>
    <p class="card-desc">
      Ping the service worker and measure round-trip latency.
    </p>
    <button
      :class="{ loading: pinging }"
      :disabled="!swReady || pinging"
      @click="runPing"
    >
      {{
        pinging
          ? `Pinging (${results.length}/${PING_COUNT})`
          : `Send ${PING_COUNT} Pings`
      }}
    </button>
    <div v-if="results.length > 0" class="ping-results">
      <div v-for="r in results" :key="r.index" class="ping-row">
        <div class="ping-bar-track">
          <div
            class="ping-bar-fill"
            :style="{
              width: `${Math.min((r.latency / MAX_PING_MS) * 100, 100)}%`,
            }"
          ></div>
        </div>
        <span class="ping-label">{{ r.latency }}ms</span>
      </div>
    </div>
    <div class="sw-result">
      <div class="result-row">
        <span>Avg Latency</span
        ><span>{{ avgLatency !== null ? `${avgLatency}ms` : "\u2014" }}</span>
      </div>
      <div class="result-row">
        <span>Pings</span><span>{{ results.length }} / {{ PING_COUNT }}</span>
      </div>
    </div>
  </div>
</template>
